# General settings
title: ICARUS personal wiki
author: Mattia Sotgia
copyright: "2026"

logo: "assets/imgs/logo/logo.gif"
email: msotgia@fnal.gov

exclude_patterns:
  - _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - LICENSE.md

execute:
  execute_notebooks: auto

bibtex_bibfiles:
  - assets/refs/references.bib

repository:
  url: https://github.com/mattiasotgia/icarus-wiki
  path_to_book: doc
  branch: doc-develop

html:
  favicon: assets/imgs/logo/favicon.ico
  baseurl: /icarus-wiki
  home_page_in_navbar: false
  use_repository_button: false
  use_issues_button: false

sphinx:
  config:
    html_show_copyright: false

  html_context:
    default_mode: light

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - smartquotes